apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cicd-demo
  region: ap-south-1

nodeGroups:
  - name: ng-1 #cluster node group name
    instanceType: t2.medium
    desiredCapacity: 3
    ssh:
      allow: false
